version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - development

  redis:
    image: redis:alpine
    ports:
      - '${REDIS_SESSION_PORT}:6379'
    volumes:
      - redis_data:/data
    profiles:
      - development

volumes:
  postgres_data:
  redis_data: