name: PR Checks

on:
  pull_request:
    branches: [ master ]

jobs:
  checks:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ fromJson(secrets.TEST_ENVS).POSTGRES_DB }}
          POSTGRES_USER: ${{ fromJson(secrets.TEST_ENVS).POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ fromJson(secrets.TEST_ENVS).POSTGRES_PASSWORD }}
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint
        
      - name: Build
        run: yarn build
        
      - name: Test
        run: yarn test:ci
        env:
          POSTGRES_DB: ${{ fromJson(secrets.TEST_ENVS).POSTGRES_DB }}
          POSTGRES_USER: ${{ fromJson(secrets.TEST_ENVS).POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ fromJson(secrets.TEST_ENVS).POSTGRES_PASSWORD }}
          DB_HOST: ${{ fromJson(secrets.TEST_ENVS).DB_HOST }}
          DB_PORT: ${{ fromJson(secrets.TEST_ENVS).DB_PORT }}
          JWT_SECRET: ${{ fromJson(secrets.TEST_ENVS).JWT_SECRET }}
          JWT_EXPIRATION_TIME: ${{ fromJson(secrets.TEST_ENVS).JWT_EXPIRATION_TIME }}
          JWT_REFRESH_SECRET: ${{ fromJson(secrets.TEST_ENVS).JWT_REFRESH_SECRET }}
          JWT_REFRESH_EXPIRATION_TIME: ${{ fromJson(secrets.TEST_ENVS).JWT_REFRESH_EXPIRATION_TIME }}
          REDIS_SESSION_PORT: ${{ fromJson(secrets.TEST_ENVS).REDIS_SESSION_PORT }}
          REDIS_BLACKLIST_PORT: ${{ fromJson(secrets.TEST_ENVS).REDIS_BLACKLIST_PORT }}
          REDIS_BLACKLIST_HOST: ${{ fromJson(secrets.TEST_ENVS).REDIS_BLACKLIST_HOST }}
          REDIS_SESSION_HOST: ${{ fromJson(secrets.TEST_ENVS).REDIS_SESSION_HOST }}
          REDIS_SESSION_DB: ${{ fromJson(secrets.TEST_ENVS).REDIS_SESSION_DB }}
          REDIS_BLACKLIST_DB: ${{ fromJson(secrets.TEST_ENVS).REDIS_BLACKLIST_DB }}
          PORT: ${{ fromJson(secrets.TEST_ENVS).PORT }}
          N: ${{ secrets.SRP_N }}
          g: ${{ fromJson(secrets.TEST_ENVS).g }}
          k: ${{ fromJson(secrets.TEST_ENVS).k }}

